name: SonarCloud

on:
  push:
    branches:
      - main
      - 'refs/tags/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Cache SonarCloud Scanner
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: sonar-cache
          restore-keys: sonar-cache

      - name: Install dependencies
        run: |
          # Run your build tool here (e.g., Maven, Gradle, npm)
          # Example for Maven:
          mvn install

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          # Run the SonarScanner (adjust the command based on your setup)
          mvn sonar:sonar \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.organization=your_organization_key \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
